# Generated by Django 6.0.6 on 2026-06-16 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_recipie_3f6dd1_idx",
            old_name="notificatio_recipie_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_recipie_4e3567_idx",
            old_name="notificatio_recipie_is_read_idx",
        ),
    ]
