# Generated by Django 6.0.5 on 2026-06-03 23:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0003_normalize_rank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammember",
            name="rank",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
