# Generated by Django 6.0.5 on 2026-06-16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0004_alter_teammember_rank"),
        ("users", "0006_user_rank"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teammember",
            name="rank",
        ),
    ]
