# Generated by Django 6.0.5 on 2026-05-19 19:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION set_deactivated_date_on_deactivation()
                    RETURNS trigger
                    LANGUAGE plpgsql
                AS
                $$
                BEGIN
                    IF
                        NEW.active IS FALSE
                            AND OLD.active IS TRUE
                            AND NEW.deactivation_date IS NULL THEN
                        NEW.deactivation_date := now();
                    END IF;

                    RETURN NEW;
                END;
                $$;

                CREATE TRIGGER set_deactivated_time
                    BEFORE UPDATE OF active
                    ON public.users_user
                    FOR EACH ROW
                EXECUTE FUNCTION set_deactivated_date_on_deactivation();
                """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS set_deactivated_time ON public.users_user;
                DROP FUNCTION IF EXISTS set_deactivated_date_on_deactivation();
                """,
        ),
    ]
