# Generated by Django 6.0.5 on 2026-05-19 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0002_add_user_deactivation_trigger"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="deleted_after_created",
        ),
        migrations.AlterField(
            model_name="admin",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("creation_date__lte", models.F("deactivation_date")),
                    ("deactivation_date__isnull", True),
                    _connector="OR",
                ),
                name="deleted_after_created",
            ),
        ),
    ]
