# Generated by Django 6.0.5 on 2026-05-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0003_remove_user_deleted_after_created_alter_admin_user_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="deleted_after_created",
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("active", True), ("deactivation_date__isnull", True)),
                    models.Q(("active", False), ("deactivation_date__isnull", False)),
                    _connector="OR",
                ),
                name="active_user_has_no_deactivation_date",
            ),
        ),
    ]
