# Generated by Django 6.0.5 on 2026-05-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_user_deleted_after_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio_text",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="job_title",
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="media/"
            ),
        ),
    ]
