# Generated by Django 6.0.5 on 2026-06-16

import django.core.validators
from django.db import migrations, models


def copy_team_member_ranks_to_users(apps, schema_editor):
    User = apps.get_model("users", "User")
    TeamMember = apps.get_model("teams", "TeamMember")

    ranks_by_user = {}
    for user_id, rank in TeamMember.objects.values_list("user_id", "rank"):
        ranks_by_user.setdefault(user_id, []).append(rank)

    for user_id, ranks in ranks_by_user.items():
        rank = (sum(ranks) + len(ranks) // 2) // len(ranks)
        rank = max(1, min(100, rank))
        User.objects.filter(pk=user_id).update(rank=rank)


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0004_alter_teammember_rank"),
        ("users", "0005_user_bio_text_user_job_title_user_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="rank",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.RunPython(
            copy_team_member_ranks_to_users,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
