# Generated by Django 6.0.5 on 2026-06-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_last_changed",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="first_password_changed",
            field=models.BooleanField(default=False),
        ),
    ]
