# Generated by Django 6.0.5 on 2026-05-19 20:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("achievements", "0002_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION func_check_confirmation_receiver()
                    RETURNS trigger
                    LANGUAGE plpgsql
                AS
                $$
                BEGIN
                    IF
                        NEW.user_id = (SELECT user_id
                                       FROM public.achievements_achievement
                                       WHERE id = NEW.achievement_id) THEN
                        RAISE EXCEPTION 'User cannot confirm their own achievement';
                    END IF;

                    RETURN NEW;
                END;
                $$;

                CREATE TRIGGER check_confirmation_receiver
                    BEFORE INSERT OR UPDATE
                    ON public.achievements_achievementconfirmation
                    FOR EACH ROW
                EXECUTE FUNCTION func_check_confirmation_receiver();
                """,
            reverse_sql="""
                    DROP TRIGGER IF EXISTS check_confirmation_receiver
                    ON public.achievements_achievementconfirmation;

                    DROP FUNCTION IF EXISTS func_check_confirmation_receiver();
                    """,
        ),
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION func_check_confirmation_request_receiver()
                    RETURNS trigger
                    LANGUAGE plpgsql
                AS
                $$
                BEGIN
                    IF
                        NEW.receiving_user_id = (SELECT user_id
                                                 FROM public.achievements_achievement
                                                 WHERE id = NEW.achievement_id) THEN
                        RAISE EXCEPTION 'User cannot request confirmation from themself';
                    END IF;

                    RETURN NEW;
                END;
                $$;

                CREATE TRIGGER check_confirmation_request_receiver
                    BEFORE INSERT OR UPDATE
                    ON public.achievements_confirmationrequest
                    FOR EACH ROW
                EXECUTE FUNCTION func_check_confirmation_request_receiver();
                """,
            reverse_sql="""
                    DROP TRIGGER IF EXISTS check_confirmation_request_receiver
                    ON public.achievements_confirmationrequest;

                    DROP FUNCTION IF EXISTS func_check_confirmation_request_receiver();
                    """,
        ),
    ]
