# Generated by Django 6.0.6 on 2026-06-16 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0002_add_tag_scope_and_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="achievementtag",
            name="added_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="glazetag",
            name="added_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
