namespace: production

resources:
  - namespace.yaml
  - ../../base

images:
  - name: ghcr.io/gorbiel/software_engineering_web_project/backend
    newTag: production
  - name: ghcr.io/gorbiel/software_engineering_web_project/frontend
    newTag: production

patches:
  - target:
      kind: Ingress
      name: frontend
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: glazedin.click

  - target:
      kind: Ingress
      name: backend
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: api.glazedin.click