namespace: production

resources:
  - namespace.yaml
  - ../../base

images:
  - name: ghcr.io/gorbiel/software_engineering_web_project/backend
    newTag: production
  - name: ghcr.io/gorbiel/software_engineering_web_project/frontend
    newTag: production

patches:
  - target:
      kind: Ingress
      name: frontend
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: glazedin.click
      - op: replace
        path: /spec/tls/0/hosts/0
        value: glazedin.click
      - op: replace
        path: /spec/tls/0/secretName
        value: production-frontend-tls

  - target:
      kind: Ingress
      name: backend
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: api.glazedin.click
      - op: replace
        path: /spec/tls/0/hosts/0
        value: api.glazedin.click
      - op: replace
        path: /spec/tls/0/secretName
        value: production-backend-tls
        

  - target:
      kind: Deployment
      name: backend
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: ENVIRONMENT
          value: "production"

  - target:
      kind: Deployment
      name: backend
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: ALLOWED_HOSTS
          value: "backend,api.glazedin.click,glazedin.click,www.glazedin.click"

  - target:
      kind: Deployment
      name: backend
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: JWT_ACCESS_TOKEN_LIFETIME_MINUTES
          value: "30"

  - target:
      kind: Deployment
      name: backend
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: JWT_REFRESH_TOKEN_LIFETIME_DAYS
          value: "30"

  - target:
      kind: Deployment
      name: backend
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: JWT_ALGORITHM
          value: "HS256"

  - target:
      kind: Deployment
      name: backend
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: CORS_ALLOWED_ORIGINS
          value: "https://glazedin.click,https://www.glazedin.click"

