namespace: production

resources:
  - namespace.yaml
  - ../../base

images:
  - name: ghcr.io/gorbiel/software_engineering_web_project/backend
    newTag: production
  - name: ghcr.io/gorbiel/software_engineering_web_project/frontend
    newTag: production

patches:
  - target:
      kind: Ingress
      name: frontend
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: glazedin.click

  - target:
      kind: Ingress
      name: backend
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: api.glazedin.click

  - target:
      kind: Deployment
      name: backend
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: ENVIRONMENT
          value: "production"

  - target:
      kind: Deployment
      name: backend
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: ALLOWED_HOSTS
          value: "api.glazedin.click,glazedin.click,www.glazedin.click"
