# Generated by Django 6.0.5 on 2026-05-19 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("glazes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="glaze",
            name="posting_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="poster",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="glaze",
            name="receiving_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receiver",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="glaze",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("posting_user__exact", models.F("receiving_user")), _negated=True
                ),
                name="user_cant_glaze_themself",
            ),
        ),
    ]
