resources:
  - backend/deployment.yaml
  - backend/service.yaml
  - backend/ingress.yaml
  - backend/pvc.yaml

  - frontend/deployment.yaml
  - frontend/service.yaml
  - frontend/ingress.yaml

  - postgres/deployment.yaml
  - postgres/service.yaml
  - postgres/pvc.yaml
