# Generated by Django 6.0.4 on 2026-05-05 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        # Automatic deactivation date assigment when setting user as non active
        migrations.RunSQL("""
                          CREATE FUNCTION set_deactivated_date_on_deactivation()
                          RETURNS trigger
                              LANGUAGE plpgsql
        AS $$
                          BEGIN
                          UPDATE public.core_user
                          SET deactivation_date = now()
                          WHERE (active IS FALSE AND deactivation_date IS NULL);
                          RETURN NEW;
                          END
        $$;

                          CREATE TRIGGER set_deactivated_time
                              AFTER UPDATE OF active
                              ON public.core_user
                              FOR EACH ROW
                              WHEN (new.active IS FALSE AND old.active is TRUE)
                              EXECUTE FUNCTION set_deactivated_date_on_deactivation();
                          """),
        # check that the user didn't confirm themself
        migrations.RunSQL(
            """
            CREATE FUNCTION func_check_confirmation_receiver()
                RETURNS trigger
    LANGUAGE plpgsql
    AS
        $$
            BEGIN
            IF
            (
            SELECT user_id_id
            FROM public.core_achievementconfirmation
            WHERE user_id_id = NEW.user_id_id LIMIT 1)
                = (SELECT user_id_id FROM public.core_achievement WHERE public.core_achievement.id = NEW.achievement_id_id LIMIT 1)
                THEN
                RAISE EXCEPTION 'User cannot confirm their own achievement';
            end if;
            RETURN NEW;
            END;
        $$;
            CREATE TRIGGER check_check_confirmation_receiver
                BEFORE INSERT
                ON public.core_achievementconfirmation
                FOR EACH ROW
                EXECUTE FUNCTION func_check_confirmation_receiver();
            """
        ),
        # check that the user didn't send a confirmation request to themself
        migrations.RunSQL(
            """
            CREATE FUNCTION func_check_confirmation_request_receiver()
                RETURNS trigger
    LANGUAGE plpgsql
    AS
        $$
            BEGIN
            IF
            (
            SELECT receiving_user_id_id
            FROM public.core_confirmationrequest
            WHERE receiving_user_id_id = NEW.receiving_user_id_id LIMIT 1)
                = (SELECT user_id_id FROM public.core_achievement WHERE public.core_achievement.id = NEW.achievement_id_id LIMIT 1)
                THEN
                RAISE EXCEPTION 'User cannot confirm their own achievement';
            end if;
            RETURN NEW;
            END;
        $$;
            CREATE TRIGGER check_check_confirmation_request_receiver
                BEFORE INSERT
                ON public.core_confirmationrequest
                FOR EACH ROW
                EXECUTE FUNCTION func_check_confirmation_request_receiver();
            """
        )
    ]
