namespace: staging

resources:
  - namespace.yaml
  - ../../base

images:
  - name: ghcr.io/gorbiel/software_engineering_web_project/backend
    newTag: 8dbdf0a
  - name: ghcr.io/gorbiel/software_engineering_web_project/frontend
    newTag: 8dbdf0a

patches:
  - target:
      kind: Ingress
      name: frontend
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: staging.glazedin.click
      - op: replace
        path: /spec/tls/0/hosts/0
        value: staging.glazedin.click
      - op: replace
        path: /spec/tls/0/secretName
        value: staging-frontend-tls

  - target:
      kind: Ingress
      name: backend
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: api.staging.glazedin.click
      - op: replace
        path: /spec/tls/0/hosts/0
        value: api.staging.glazedin.click
      - op: replace
        path: /spec/tls/0/secretName
        value: staging-backend-tls
        

  - target:
      kind: Deployment
      name: backend
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: ENVIRONMENT
          value: "dev"

  - target:
      kind: Deployment
      name: backend
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: ALLOWED_HOSTS
          value: "backend,api.staging.glazedin.click,staging.glazedin.click"

  - target:
      kind: Deployment
      name: backend
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: JWT_ACCESS_TOKEN_LIFETIME_MINUTES
          value: "30"

  - target:
      kind: Deployment
      name: backend
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: JWT_REFRESH_TOKEN_LIFETIME_DAYS
          value: "30"

  - target:
      kind: Deployment
      name: backend
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: JWT_ALGORITHM
          value: "HS256"

  - target:
      kind: Deployment
      name: backend
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: CORS_ALLOWED_ORIGINS
          value: "https://staging.glazedin.click"
