namespace: staging

resources:
  - namespace.yaml
  - ../../base

images:
  - name: ghcr.io/gorbiel/software_engineering_web_project/backend
    newTag: staging
  - name: ghcr.io/gorbiel/software_engineering_web_project/frontend
    newTag: staging

patches:
  - target:
      kind: Deployment
      name: backend
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: ALLOWED_HOSTS
          value: "api.staging.glazedin.click,staging.glazedin.click"
