# Generated by Django 6.0.5 on 2026-05-19 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("glazes", "0002_initial"),
        ("reactions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="achievementreaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="glazereaction",
            name="glaze",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="glazes.glaze"
            ),
        ),
        migrations.AddField(
            model_name="glazereaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="glazereaction",
            name="reaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="reactions.reaction"
            ),
        ),
        migrations.AddField(
            model_name="achievementreaction",
            name="reaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="reactions.reaction"
            ),
        ),
    ]
